import pyautogui as pyag
import sys
import os
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from flask import Flask, request

app = Flask(__name__)
os.environ['FLASK_ENV'] = 'production'

if sys.version_info[0] < 3:
    raise Exception("NOTE: YOU ARE USING PYTHON VERSION 2, RECOMMENDED THAT YOU UPGRADE TO VERSION 3.")

# initialize | get on the website & accept cookies
driver = webdriver.Firefox()
driver.get("https://monkeytype.com/")
driver.find_element(By.XPATH, "/html/body/div[8]/dialog/div[2]/div[2]/div[2]/button[1]").click()

def setupTest():

    # put textbox on screen
    # put start button on screen
    driver.execute_script("""
        var delayTextbox = document.createElement("input");
        delayTextbox.setAttribute("type", "text");
        delayTextbox.setAttribute("id", "myInput");
        delayTextbox.setAttribute("placeholder", "Keypress delay (seconds)");

        var startButton = document.createElement("button");
        startButton.setAttribute("type", "button");
        startButton.setAttribute("id", "startBotButton");
        startButton.textContent = "Start bot";

        var targetElement = document.querySelector(".page > div:nth-child(5)");
        targetElement.appendChild(delayTextbox);
        targetElement.appendChild(startButton);
    """)

    # put code for checking text
    # put code for when button is pressed -> trigger python
    # below generated by chatgpt
    driver.execute_script("""
        document.getElementById("startBotButton").addEventListener("click", function() {
            // Retrieve the value from the input text box
            var inputValue = document.getElementById("myInput").value;
                          
            if (!inputValue) {
                inputValue = 0;
            }

            // Use AJAX to send the value to a server-side Python script
            var xhr = new XMLHttpRequest();
            xhr.open("GET", "http://localhost:5000/python_script?inputValue=" + encodeURIComponent(inputValue), true);
            xhr.onreadystatechange = function() {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    console.log(xhr.responseText);
                }
            };
            xhr.send();
        });
    """)

# below made by me w help of chatgpt
@app.route('/python_script')
def python_script():
    inputValue = request.args.get('inputValue')
    botScript(inputValue)
    return "win"

def botScript(delay):
    print("hello! " + delay)

    # add code for the actual bot script later :) -4/13/24

if __name__ == "__main__":
    setupTest()
    print("\n\nIf no errors occurred below, then you can minimize this window unless you're debugging\nIf no errors occurred below, then you can minimize this window unless you're debugging\nIf no errors occurred below, then you can minimize this window unless you're debugging\n\n")
    app.run(debug=False)
